Added package signing.

diff --git a/.github/scripts/build-package b/.github/scripts/build-package
--- a/.github/scripts/build-package
+++ b/.github/scripts/build-package
@@ -12,7 +12,9 @@ VERSION="11 (bullseye)"
 . /etc/os-release
 
 SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
-cd ${SCRIPTDIR}/../..
+SECRETSDIR="${SCRIPTDIR}/../secrets"
+
+cd "${SCRIPTDIR}/../.."
 
 export DEBIAN_FRONTEND=noninteractive
 apt-get update > /dev/null
@@ -51,11 +53,11 @@ RAW_VERSION="$(dpkg-parsechangelog --show-field Version | cut -d'+' -f1)"
 
 if [ "${ID}" == "ubuntu" ]
 then
-    NEW_VERSION="${RAW_VERSION}+u$(echo ${VERSION_ID} | sed s#\\.##g)"
+    NEW_VERSION="${RAW_VERSION}+u${VERSION_ID//./}"
 elif [ "${ID}" == "debian" ]
 then
-    NEW_VERSION="${RAW_VERSION}+deb$(echo ${VERSION_ID} | sed s#\\.##g)"
-    VERSION_CODENAME=$(echo ${VERSION} | awk -F"[)(]+" '{print $2}')
+    NEW_VERSION="${RAW_VERSION}+deb${VERSION_ID//./}"
+    VERSION_CODENAME=$(echo "${VERSION}" | awk -F"[)(]+" '{print $2}')
 else
     >&2 echo "Error: unhandled operating system id (${ID})!"
     exit 1
@@ -80,11 +82,11 @@ VERSION_HELPERS="edi/lib/versionhelpers.py"
 sed -i "s/^edi_fallback_version =.*/edi_fallback_version = '${NEW_VERSION}'/g" ${VERSION_HELPERS}
 sudo -u ${TESTUSER} git add ${VERSION_HELPERS}
 
-dch -b --newversion ${NEW_VERSION} --distribution ${VERSION_CODENAME} -m "Automatic ${VERSION_CODENAME} build."
+dch -b --newversion "${NEW_VERSION}" --distribution "${VERSION_CODENAME}" -m "Automatic ${VERSION_CODENAME} build."
 
 sudo -u ${TESTUSER} git add debian/changelog
 sudo -u ${TESTUSER} git commit -m "New version ${NEW_VERSION}."
-sudo -u ${TESTUSER} git tag -a v${NEW_VERSION} -m "New version ${NEW_VERSION}."
+sudo -u ${TESTUSER} git tag -a "v${NEW_VERSION}" -m "New version ${NEW_VERSION}."
 
 mk-build-deps -i debian/control -t "apt-get -y" > /dev/null
 
@@ -106,62 +108,35 @@ then
     exit 1
 fi
 
-if [ "${ID}" == "ubuntuXXX" ]
+if [ "${ID}" == "ubuntu" ]
 then
-    GPG_MAJOR_VERSION=$(gpg --version | head -n1 | cut -d' ' -f3 | cut -d'.' -f1)
+    sudo -u ${TESTUSER} git clean -dxf
 
-    GPG_OPTIONS="--pinentry-mode loopback"
-    if [ "${GPG_MAJOR_VERSION}" == "1" ]
+    GPG_KEY="${SECRETSDIR}/launchpad-key.asc"
+    GPG_KEY_PASSPHRASE="${SECRETSDIR}/launchpad-key.passphrase"
+
+    if [[ ! -f "${GPG_KEY}" ]] || [[ ! -f "${GPG_KEY_PASSPHRASE}" ]]
     then
-        GPG_OPTIONS="--batch --yes --no-use-agent"
-    fi
-
-    GPG_ARCHIVE="${SCRIPTDIR}/travis-key.tar"
-
-    if [ ! -f "${GPG_ARCHIVE}" ]
-    then
-        >&2 echo -e "\nError: Missing credential archive ${GPG_ARCHIVE}."
+        >&2 echo -e "\nError: Missing gpg key ${GPG_KEY} or passphrase ${GPG_KEY_PASSPHRASE}."
         exit 1
     fi
 
-    sudo -u ${TESTUSER} git clean -dxf
-    sudo -u ${TESTUSER} tar -xf ${GPG_ARCHIVE} -C ${CONTAINER_WORK}/travis/
-
-    GPG_KEY="${CONTAINER_WORK}/travis/travis-key.asc"
-    GPG_KEY_PASSPHRASE="${CONTAINER_WORK}/travis/travis-key.passphrase"
-    gpg ${GPG_OPTIONS} --passphrase-file ${GPG_KEY_PASSPHRASE} --import ${GPG_KEY}
+    gpg --pinentry-mode loopback --passphrase-file "${GPG_KEY_PASSPHRASE}" --import "${GPG_KEY}"
 
     sudo -u ${TESTUSER} debuild -S -us -uc > /dev/null
 
     RESULT="${CONTAINER_WORK}/../edi_${NEW_VERSION}_source.changes"
-    debsign -p"gpg ${GPG_OPTIONS} --passphrase-file ${GPG_KEY_PASSPHRASE}" -S -kB6D5610F601C6B6E4A880C93AA6945FE5AAFB25D ${RESULT}
-
-    GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
-    if [ "${GIT_BRANCH}" == "master" ]
-    then
-        apt-get --no-install-recommends -y install openssh-client dput locales python3-paramiko > /dev/null
-        locale-gen en_US.UTF-8
-        export LANG=en_US.UTF-8
-
-        SSH_FOLDER=/root/.ssh
-        mkdir ${SSH_FOLDER}
-        chmod 0700 ${SSH_FOLDER}
-
-        cp ${CONTAINER_WORK}/travis/id_rsa ${SSH_FOLDER}/
-        cp ${CONTAINER_WORK}/travis/id_rsa.pub ${SSH_FOLDER}/
-        cp ${CONTAINER_WORK}/travis/known_hosts ${SSH_FOLDER}/
-        chmod -R 0600 ${SSH_FOLDER}/*
-
-        ssh-keyscan ppa.launchpad.net >> ${SSH_FOLDER}/known_hosts
-
-        dput --unchecked --config ${CONTAINER_WORK}/travis/dput.cf ppa:m-luescher/edi-snapshots ${RESULT}
-    else
-        echo "Skipping deployment on ${GIT_BRANCH} branch."
-    fi
-else
-    BUILD_OUTPUT="${SCRIPTDIR}/../../"
-    cp -f ../edi_${NEW_VERSION}* ${BUILD_OUTPUT}
+    debsign -p"gpg --pinentry-mode loopback --passphrase-file ${GPG_KEY_PASSPHRASE}" -S -kB6D5610F601C6B6E4A880C93AA6945FE5AAFB25D "${RESULT}"
 fi
+    
+BUILD_OUTPUT="${SCRIPTDIR}/../../build-output"
+mkdir -p "${BUILD_OUTPUT}"
+cp -f ../edi_"${NEW_VERSION}"* "${BUILD_OUTPUT}"
+
+cat << EOF > "${BUILD_OUTPUT}/build-info"
+PACKAGE_NAME=edi
+PACKAGE_VERSION=${NEW_VERSION}
+EOF
 
 echo "========"
 echo "Success!"
